<?php 	$this->headscript()->appendFile($this->basePath() . '/js/index/index.js');?>
<div class="heading">
	<div class="text">
		<ul class="nav nav-tabs">
			<li class="active"><a href="#sensorReadingsTab" data-toggle="tab">Sensor Readings</a></li>
			<li><a href="#sensorGraphTab" data-toggle="tab">Sensor Graph</a></li>
		</ul>
	</div>
	<div class="button"><span id="pumpOn" class="btn btn-primary">Turn Pump On</span></div>
</div>

<div class="tab-content">
	<!-- Sensor readings tab -->
	<div id="sensorReadingsTab" class="tab-pane active">
		<?php if ($this->sensors) : ?>
			<div class="sensorReadings">
			<?php
				//output the latest sensor values
				$i = 0;
				foreach ($this->sensors as $sensor) {
					//open the row for every 4th element
					if ($i % 4 == 0) echo '<div>';
					//output the sensor details
					echo $this->partial('watering-system/partials/sensordisplay.phtml', array('sensor' => $sensor));
					//close the row for every 4th element
					if ($i % 4 == 3) echo '</div>';
					//we need this to clear the divs on small displays otherwise we can get misaligned rows
					if ($i % 4 == 1) echo '<div class="clearfix visible-xs"></div>';
					$i++;
				}
				//we need this line to close the last row if it wasn't 4 elements wide
				if ($i % 4 != 3) echo '</div>';
			?>
			</div>
		<?php else : ?>
			<p>No sensor readings found</p>
		<?php endif;?>
	</div>
	<!-- Sensor graph tab -->
	<div id="sensorGraphTab" class="tab-pane">
		<?php if ($this->sensorValues) : ?>
			<?php echo $this->partial('watering-system/partials/sensorgraph.phtml', array('sensorValues' => $this->sensorValues)); ?>
		<?php else : ?>
			<p>No sensor values found</p>
		<?php endif;?>
	</div>
</div>