<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Watering System'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Stylesheets -->
        <?php 
        	echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/css/site.css');
        ?>

        <!-- Scripts -->
        <?php 
        	echo $this->headScript()
            ->prependFile($this->basePath() . '/js/site.js')
//             ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
//             ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));
		?>
</head>
<body>
	<div class="container">
		<div class="header">
			<ul class="nav nav-pills pull-right">
				<li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
				<!-- <li><a href="#">About</a></li>  -->
			</ul>
			<h3 class="text-muted"><?php echo $this->translate('Watering System') ?></h3>
		</div>
		
		<div class="content">
			<div>
      			<?php echo $this->content; ?>
      		</div>
      	</div>
		<div class="footer">
			<p>&copy; Cooke IT 2014</p>
		</div>
	</div> <!-- /container -->
	<?php echo $this->inlineScript()?>
</body>
</html>
