<div class="sensorReadings">
<?php
	$id = $this->node->getId();
	//output the latest sensor values
	foreach ($this->sensors as $sensor) {
		//skip if sensor is disabled
		if (!$sensor->getIsEnabled()) continue;
		
		//clear at opening to fix margins when responsive
		if ($this->counter()->isFirstInColumn('clear'.$id, $this->columns)) echo '<div class="clearfix visible-xs"></div>';
		//open the column
		if ($this->counter()->isFirstInColumn('open'.$id, $this->columns)) echo '<div>';
			//output the sensor details
			echo $this->partial('watering-system/partials/sensordisplay.phtml', array('sensor' => $sensor));
		//close the row at the end of the column
		if ($this->counter()->isLastInColumn('close'.$id, $this->columns)) echo '</div>';
	}
	//close the last row if it wasn't the exact width
	if (!$this->counter()->isLastInColumn('finish'.$id, $this->columns)) echo '</div>';
?>
</div>