<?php 
use WateringSystem\Entity\Sensor;
use WateringSystem\Entity\SensorValue;
$sensor = $this->sensor;
if ($sensor instanceof Sensor == false) return;
?>

<div class="sensorReading">
	<div>
		<div class="title">
			<?php echo $this->escapehtml($this->sensor->getDescription()); ?>
		</div>
		<div class="value">
		<?php 
			$sensorValue = $this->sensorvalue($sensor);
			if ($sensorValue instanceof SensorValue) {
				switch ($sensorValue->getSensor()->getValueType()) {
					case Sensor::TYPE_BOOLEAN :
						echo $sensorValue->getValue() ? 'On' : 'Off';
						break;
					default:
						echo $this->escapehtml($sensorValue->getCalibratedValue() . $sensor->getUnits());
						break;
				}
			} else {
				echo '--';
			}
		?>
		</div>
		<div class="time">
			<small><?php if ($sensorValue instanceof SensorValue) { echo $this->fuzzyDate($sensorValue->getDate()); }?></small>
		</div>
		<?php if ($sensor->getIsRanged()) : ?>
		<div class="progress progress-striped">
			<?php if ($sensorValue instanceof SensorValue) : ?>
				<?php $percent = (int) ($sensorValue->getCalibratedValue() / $sensor->getRange() * 100); ?>
			<div class="progress-bar progress-bar-info" style="width: <?php echo $percent?>%"></div>
			<?php endif; ?>
		</div>
		<?php endif; ?>
	</div>
</div>