<?php
	$this->headscript()->prependFile($this->basePath() . '/js/partials/sensorgraph.js');
?>
<?php $this->headScript()->captureStart() ?>
jQuery(document).ready(function($){
	$('<?php echo $this->container?>').find('.sensorGraph').sensorgraph({
		node:	<?php echo $this->node; ?>
	});
});
<?php $this->headScript()->captureEnd() ?>
<div class="sensorGraph">
	<div class="chartLoader"></div>
	<div class="chartContainer">
		<div class="chart rickshaw_graph"></div>
		<div class="slider"></div>
		<div class="legend_container">
			<div class="legend rickshaw_legend"></div>
		</div>
		<div class="fetchResults"><small>&lt; get earlier results</small></div>
	</div>
</div>