<?php
	$sensorValues = $this->sensorValues;
	if (!is_array($sensorValues) || count($sensorValues) == 0) return;
	$this->headscript()->prependFile($this->basePath() . '/js/partials/sensorgraph.js');
?>
<?php $this->headScript()->captureStart() ?>
jQuery(document).ready(function($){
	$('<?php echo $this->container?>').find('.sensorGraph').sensorgraph({
		values: <?php echo $this->sensorToJson()->getGraphData($sensorValues); ?> 
	});
});
<?php $this->headScript()->captureEnd() ?>
<div class="sensorGraph">
	<div class="chart rickshaw_graph"></div>
	<div class="slider"></div>
	<div class="legend_container">
		<div class="legend rickshaw_legend"></div>
	</div>
	<!-- functionality to be readded <div class="fetchResults"><small>&lt; get earlier results</small></div>  -->
</div>